update

diff --git a/scripts/puttypos b/scripts/puttypos
--- a/scripts/puttypos
+++ b/scripts/puttypos
@@ -110,6 +110,9 @@ if [ "$1" = "auto" ]; then
 
    # loop through the file to find the line that matches the "putty_login,putty_ip"
    tmpfile=/tmp/puttypos.$putty_login.$putty_ip
+   /bin/rm -f $tmpfile
+
+   [ $verbose = Y ] && echo "searching for putty client line in $putty_client_file for pattern='^$putty_login,$putty_ip'"
    cat $putty_client_file | while read line; do
       # echo "line=$line"
       if [[ $line =~ ^$putty_login, ]]; then
@@ -128,17 +131,18 @@ if [ "$1" = "auto" ]; then
       line=$(cat $tmpfile)
       rm -f $tmpfile
    else
-      line=""
+      [ $verbose = Y ] && echo "ERROR: no putty client found in $putty_client_file for pattern='^$putty_login,$putty_ip'" >&2
+      exit 1
    fi
    [ $verbose = Y ] && echo "line=$line"
    
-   # # if there is a line, then we can set the putty position
-   # if [ "X$line" = "X" ]; then
-   #    [ $verbose = Y ] && echo "ERROR: no putty client found in $putty_client_file for pattern='^$putty_login,$putty_ip'" >&2
-   #    exit 1
-   # elif [ $verbose = Y ]; then
-   #    echo "found putty client line: $line"
-   # fi
+   # if there is a line, then we can set the putty position
+   if [ "X$line" = "X" ]; then
+      [ $verbose = Y ] && echo "ERROR: no putty client found in $putty_client_file for pattern='^$putty_login,$putty_ip'" >&2
+      exit 1
+   elif [ $verbose = Y ]; then
+      echo "found putty client line: $line"
+   fi
 
    min_pos=$(echo $line | awk '{print $2}')
    max_pos=$(echo $line | awk '{print $3}')
